baseURL = "/"
languageCode = "en-us"
title = "Practical DL"
theme = "ink"

paginate = 5

copyright = "© Peter Izsak"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true 
    lineNumbersInTable = true
    noClasses = true
    style = "friendly"
    tabWidth = 2

# pygmentsUseClasses=true
# pygmentsstyle = "monokai"
# pygmentscodefences = true
# pygmentscodefencesguesssyntax = true

[params]
	subtitle = "Neural Networks best practices, tutorials and personal blog"

	# Optional 64x64 avatar image.
	# avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "light" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "About"
url = "/about"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/peteriz"

[taxonomies]
   tag = "tags"
